version: 1
formatters:
  first:
    format: '%(levelname)s:%(asctime)s:%(name)s:%(message)s'
    datefmt: '[%d.%m.%Y %H:%M]'

  second: 
    format: '%(asctime)s %(message)s'
    datefmt: '[%d.%m.%Y %H:%M]'

  third:
    format: '%(message)s'

handlers:
  sm:
    class: logging.FileHandler
    level: DEBUG
    formatter: first
    filename: sender.log
    mode: 'w'

  rm:
    class: logging.FileHandler
    level: DEBUG
    formatter: second
    filename: reader.log
    mode: 'a'

  wm:
    class: logging.FileHandler
    level: DEBUG
    formatter: third
    filename: watch.log
    mode: 'w'

  default:
    class: logging.FileHandler
    level: DEBUG
    filename: default.log
    mode: 'w'


loggers:
  sender:
    level: DEBUG
    handlers: [sm]
    propagate: no

  reader:
    level: DEBUG
    handlers: [rm]
    propagate: no

  watcher:
    level: DEBUG
    handlers: [wm]
    propagate: no 

  default:
    level: DEBUG
    handlers: [default]
    propagate: no

root:
  level: DEBUG
  